"""
UB-04 (CMS-1450) Institutional Claim Schema.

Defines the complete schema for extracting data from UB-04 forms,
the standard billing form used by institutional providers such as
hospitals, skilled nursing facilities, and home health agencies.
"""

from src.schemas.base import DocumentSchema, DocumentType, SchemaRegistry
from src.schemas.field_types import CrossFieldRule, FieldDefinition, FieldType, RuleOperator


# =============================================================================
# UB-04 Field Definitions
# =============================================================================

# Provider Information (Form Locators 1-11)
PROVIDER_FIELDS = [
    FieldDefinition(
        name="billing_provider_name",
        display_name="Billing Provider Name (FL 1)",
        field_type=FieldType.STRING,
        description="Name of the billing provider/facility",
        required=True,
        location_hint="Form Locator 1 - Top left of form",
        examples=["GENERAL HOSPITAL", "MEMORIAL MEDICAL CENTER"],
    ),
    FieldDefinition(
        name="billing_provider_address",
        display_name="Billing Provider Address (FL 1)",
        field_type=FieldType.ADDRESS,
        description="Street address of the billing provider",
        required=True,
        location_hint="Form Locator 1 - Below provider name",
    ),
    FieldDefinition(
        name="billing_provider_city",
        display_name="Billing Provider City (FL 1)",
        field_type=FieldType.STRING,
        description="City of the billing provider",
        required=True,
        location_hint="Form Locator 1 - Address line",
    ),
    FieldDefinition(
        name="billing_provider_state",
        display_name="Billing Provider State (FL 1)",
        field_type=FieldType.STATE,
        description="State of the billing provider (2-letter code)",
        required=True,
        location_hint="Form Locator 1 - Address line",
    ),
    FieldDefinition(
        name="billing_provider_zip",
        display_name="Billing Provider ZIP (FL 1)",
        field_type=FieldType.ZIP_CODE,
        description="ZIP code of the billing provider",
        required=True,
        location_hint="Form Locator 1 - Address line",
    ),
    FieldDefinition(
        name="billing_provider_phone",
        display_name="Billing Provider Phone (FL 1)",
        field_type=FieldType.PHONE,
        description="Phone number of the billing provider",
        required=False,
        location_hint="Form Locator 1 - Near address",
    ),
    FieldDefinition(
        name="pay_to_name",
        display_name="Pay-To Name (FL 2)",
        field_type=FieldType.STRING,
        description="Pay-to name if different from billing provider",
        required=False,
        location_hint="Form Locator 2",
    ),
    FieldDefinition(
        name="pay_to_address",
        display_name="Pay-To Address (FL 2)",
        field_type=FieldType.ADDRESS,
        description="Pay-to address if different from billing provider",
        required=False,
        location_hint="Form Locator 2",
    ),
    FieldDefinition(
        name="patient_control_number",
        display_name="Patient Control Number (FL 3a)",
        field_type=FieldType.STRING,
        description="Patient's unique control number assigned by provider",
        required=True,
        location_hint="Form Locator 3a",
        pattern=r"^[A-Za-z0-9\-]{1,24}$",
    ),
    FieldDefinition(
        name="medical_record_number",
        display_name="Medical Record Number (FL 3b)",
        field_type=FieldType.STRING,
        description="Patient's medical record number",
        required=False,
        location_hint="Form Locator 3b",
    ),
    FieldDefinition(
        name="type_of_bill",
        display_name="Type of Bill (FL 4)",
        field_type=FieldType.STRING,
        description="4-digit type of bill code (facility type + bill classification + frequency)",
        required=True,
        location_hint="Form Locator 4",
        pattern=r"^[01]\d{3}$",
        examples=["0111", "0121", "0131", "0211", "0321"],
    ),
    FieldDefinition(
        name="federal_tax_id",
        display_name="Federal Tax ID (FL 5)",
        field_type=FieldType.STRING,
        description="Provider's federal tax identification number",
        required=True,
        location_hint="Form Locator 5",
        pattern=r"^\d{2}-?\d{7}$",
    ),
    FieldDefinition(
        name="statement_from_date",
        display_name="Statement Covers Period From (FL 6)",
        field_type=FieldType.DATE,
        description="Start date of the billing period",
        required=True,
        location_hint="Form Locator 6 - From date",
    ),
    FieldDefinition(
        name="statement_to_date",
        display_name="Statement Covers Period To (FL 6)",
        field_type=FieldType.DATE,
        description="End date of the billing period",
        required=True,
        location_hint="Form Locator 6 - To date",
    ),
]

# Patient Information (Form Locators 8-17)
PATIENT_FIELDS = [
    FieldDefinition(
        name="patient_name",
        display_name="Patient Name (FL 8a)",
        field_type=FieldType.NAME,
        description="Patient's full name (Last, First, MI)",
        required=True,
        location_hint="Form Locator 8a",
        examples=["DOE, JOHN A", "SMITH, MARY"],
    ),
    FieldDefinition(
        name="patient_address",
        display_name="Patient Address (FL 9a)",
        field_type=FieldType.ADDRESS,
        description="Patient's street address",
        required=True,
        location_hint="Form Locator 9a",
    ),
    FieldDefinition(
        name="patient_city",
        display_name="Patient City (FL 9b)",
        field_type=FieldType.STRING,
        description="Patient's city",
        required=True,
        location_hint="Form Locator 9b",
    ),
    FieldDefinition(
        name="patient_state",
        display_name="Patient State (FL 9c)",
        field_type=FieldType.STATE,
        description="Patient's state",
        required=True,
        location_hint="Form Locator 9c",
    ),
    FieldDefinition(
        name="patient_zip",
        display_name="Patient ZIP (FL 9d)",
        field_type=FieldType.ZIP_CODE,
        description="Patient's ZIP code",
        required=True,
        location_hint="Form Locator 9d",
    ),
    FieldDefinition(
        name="patient_dob",
        display_name="Patient Date of Birth (FL 10)",
        field_type=FieldType.DATE,
        description="Patient's date of birth",
        required=True,
        location_hint="Form Locator 10",
    ),
    FieldDefinition(
        name="patient_sex",
        display_name="Patient Sex (FL 11)",
        field_type=FieldType.STRING,
        description="Patient's sex (M or F)",
        required=True,
        allowed_values=["M", "F"],
        location_hint="Form Locator 11",
    ),
    FieldDefinition(
        name="admission_date",
        display_name="Admission Date (FL 12)",
        field_type=FieldType.DATE,
        description="Date patient was admitted",
        required=True,
        location_hint="Form Locator 12",
    ),
    FieldDefinition(
        name="admission_hour",
        display_name="Admission Hour (FL 13)",
        field_type=FieldType.STRING,
        description="Hour of admission (00-23)",
        required=False,
        location_hint="Form Locator 13",
        pattern=r"^([01]\d|2[0-3])$",
    ),
    FieldDefinition(
        name="admission_type",
        display_name="Type of Admission (FL 14)",
        field_type=FieldType.STRING,
        description="Priority type of admission code",
        required=True,
        allowed_values=["1", "2", "3", "4", "5", "9"],
        location_hint="Form Locator 14",
        examples=["1", "2", "3"],  # 1=Emergency, 2=Urgent, 3=Elective
    ),
    FieldDefinition(
        name="admission_source",
        display_name="Source of Admission (FL 15)",
        field_type=FieldType.STRING,
        description="Code indicating source of admission",
        required=True,
        location_hint="Form Locator 15",
        pattern=r"^[1-9A-F]$",
        examples=["1", "2", "4", "5", "7"],
    ),
    FieldDefinition(
        name="discharge_hour",
        display_name="Discharge Hour (FL 16)",
        field_type=FieldType.STRING,
        description="Hour of discharge (00-23)",
        required=False,
        location_hint="Form Locator 16",
        pattern=r"^([01]\d|2[0-3])$",
    ),
    FieldDefinition(
        name="patient_status",
        display_name="Patient Discharge Status (FL 17)",
        field_type=FieldType.STRING,
        description="Status of patient at discharge",
        required=True,
        location_hint="Form Locator 17",
        pattern=r"^\d{2}$",
        examples=["01", "02", "03", "04", "20", "30"],
    ),
]

# Condition Codes (Form Locators 18-28)
CONDITION_CODE_FIELDS = [
    FieldDefinition(
        name="condition_code_1",
        display_name="Condition Code 1 (FL 18)",
        field_type=FieldType.STRING,
        description="Condition code 1",
        required=False,
        location_hint="Form Locator 18",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_2",
        display_name="Condition Code 2 (FL 19)",
        field_type=FieldType.STRING,
        description="Condition code 2",
        required=False,
        location_hint="Form Locator 19",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_3",
        display_name="Condition Code 3 (FL 20)",
        field_type=FieldType.STRING,
        description="Condition code 3",
        required=False,
        location_hint="Form Locator 20",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_4",
        display_name="Condition Code 4 (FL 21)",
        field_type=FieldType.STRING,
        description="Condition code 4",
        required=False,
        location_hint="Form Locator 21",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_5",
        display_name="Condition Code 5 (FL 22)",
        field_type=FieldType.STRING,
        description="Condition code 5",
        required=False,
        location_hint="Form Locator 22",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_6",
        display_name="Condition Code 6 (FL 23)",
        field_type=FieldType.STRING,
        description="Condition code 6",
        required=False,
        location_hint="Form Locator 23",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_7",
        display_name="Condition Code 7 (FL 24)",
        field_type=FieldType.STRING,
        description="Condition code 7",
        required=False,
        location_hint="Form Locator 24",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_8",
        display_name="Condition Code 8 (FL 25)",
        field_type=FieldType.STRING,
        description="Condition code 8",
        required=False,
        location_hint="Form Locator 25",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_9",
        display_name="Condition Code 9 (FL 26)",
        field_type=FieldType.STRING,
        description="Condition code 9",
        required=False,
        location_hint="Form Locator 26",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_10",
        display_name="Condition Code 10 (FL 27)",
        field_type=FieldType.STRING,
        description="Condition code 10",
        required=False,
        location_hint="Form Locator 27",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="condition_code_11",
        display_name="Condition Code 11 (FL 28)",
        field_type=FieldType.STRING,
        description="Condition code 11",
        required=False,
        location_hint="Form Locator 28",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="accident_state",
        display_name="Accident State (FL 29)",
        field_type=FieldType.STATE,
        description="State where accident occurred",
        required=False,
        location_hint="Form Locator 29",
    ),
]

# Occurrence Codes and Dates (Form Locators 31-34)
OCCURRENCE_FIELDS = [
    FieldDefinition(
        name="occurrence_code_1",
        display_name="Occurrence Code 1 (FL 31a)",
        field_type=FieldType.STRING,
        description="Occurrence code 1",
        required=False,
        location_hint="Form Locator 31a - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_date_1",
        display_name="Occurrence Date 1 (FL 31a)",
        field_type=FieldType.DATE,
        description="Date for occurrence code 1",
        required=False,
        location_hint="Form Locator 31a - Date",
    ),
    FieldDefinition(
        name="occurrence_code_2",
        display_name="Occurrence Code 2 (FL 31b)",
        field_type=FieldType.STRING,
        description="Occurrence code 2",
        required=False,
        location_hint="Form Locator 31b - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_date_2",
        display_name="Occurrence Date 2 (FL 31b)",
        field_type=FieldType.DATE,
        description="Date for occurrence code 2",
        required=False,
        location_hint="Form Locator 31b - Date",
    ),
    FieldDefinition(
        name="occurrence_code_3",
        display_name="Occurrence Code 3 (FL 32a)",
        field_type=FieldType.STRING,
        description="Occurrence code 3",
        required=False,
        location_hint="Form Locator 32a - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_date_3",
        display_name="Occurrence Date 3 (FL 32a)",
        field_type=FieldType.DATE,
        description="Date for occurrence code 3",
        required=False,
        location_hint="Form Locator 32a - Date",
    ),
    FieldDefinition(
        name="occurrence_code_4",
        display_name="Occurrence Code 4 (FL 32b)",
        field_type=FieldType.STRING,
        description="Occurrence code 4",
        required=False,
        location_hint="Form Locator 32b - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_date_4",
        display_name="Occurrence Date 4 (FL 32b)",
        field_type=FieldType.DATE,
        description="Date for occurrence code 4",
        required=False,
        location_hint="Form Locator 32b - Date",
    ),
    FieldDefinition(
        name="occurrence_code_5",
        display_name="Occurrence Code 5 (FL 33a)",
        field_type=FieldType.STRING,
        description="Occurrence code 5",
        required=False,
        location_hint="Form Locator 33a - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_date_5",
        display_name="Occurrence Date 5 (FL 33a)",
        field_type=FieldType.DATE,
        description="Date for occurrence code 5",
        required=False,
        location_hint="Form Locator 33a - Date",
    ),
    FieldDefinition(
        name="occurrence_code_6",
        display_name="Occurrence Code 6 (FL 33b)",
        field_type=FieldType.STRING,
        description="Occurrence code 6",
        required=False,
        location_hint="Form Locator 33b - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_date_6",
        display_name="Occurrence Date 6 (FL 33b)",
        field_type=FieldType.DATE,
        description="Date for occurrence code 6",
        required=False,
        location_hint="Form Locator 33b - Date",
    ),
    FieldDefinition(
        name="occurrence_code_7",
        display_name="Occurrence Code 7 (FL 34a)",
        field_type=FieldType.STRING,
        description="Occurrence code 7",
        required=False,
        location_hint="Form Locator 34a - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_date_7",
        display_name="Occurrence Date 7 (FL 34a)",
        field_type=FieldType.DATE,
        description="Date for occurrence code 7",
        required=False,
        location_hint="Form Locator 34a - Date",
    ),
    FieldDefinition(
        name="occurrence_code_8",
        display_name="Occurrence Code 8 (FL 34b)",
        field_type=FieldType.STRING,
        description="Occurrence code 8",
        required=False,
        location_hint="Form Locator 34b - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_date_8",
        display_name="Occurrence Date 8 (FL 34b)",
        field_type=FieldType.DATE,
        description="Date for occurrence code 8",
        required=False,
        location_hint="Form Locator 34b - Date",
    ),
]

# Occurrence Span Codes (Form Locators 35-36)
OCCURRENCE_SPAN_FIELDS = [
    FieldDefinition(
        name="occurrence_span_code_1",
        display_name="Occurrence Span Code 1 (FL 35a)",
        field_type=FieldType.STRING,
        description="Occurrence span code 1",
        required=False,
        location_hint="Form Locator 35a - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_span_from_1",
        display_name="Occurrence Span From Date 1 (FL 35a)",
        field_type=FieldType.DATE,
        description="Start date for occurrence span 1",
        required=False,
        location_hint="Form Locator 35a - From",
    ),
    FieldDefinition(
        name="occurrence_span_to_1",
        display_name="Occurrence Span To Date 1 (FL 35a)",
        field_type=FieldType.DATE,
        description="End date for occurrence span 1",
        required=False,
        location_hint="Form Locator 35a - To",
    ),
    FieldDefinition(
        name="occurrence_span_code_2",
        display_name="Occurrence Span Code 2 (FL 35b)",
        field_type=FieldType.STRING,
        description="Occurrence span code 2",
        required=False,
        location_hint="Form Locator 35b - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_span_from_2",
        display_name="Occurrence Span From Date 2 (FL 35b)",
        field_type=FieldType.DATE,
        description="Start date for occurrence span 2",
        required=False,
        location_hint="Form Locator 35b - From",
    ),
    FieldDefinition(
        name="occurrence_span_to_2",
        display_name="Occurrence Span To Date 2 (FL 35b)",
        field_type=FieldType.DATE,
        description="End date for occurrence span 2",
        required=False,
        location_hint="Form Locator 35b - To",
    ),
    FieldDefinition(
        name="occurrence_span_code_3",
        display_name="Occurrence Span Code 3 (FL 36a)",
        field_type=FieldType.STRING,
        description="Occurrence span code 3",
        required=False,
        location_hint="Form Locator 36a - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_span_from_3",
        display_name="Occurrence Span From Date 3 (FL 36a)",
        field_type=FieldType.DATE,
        description="Start date for occurrence span 3",
        required=False,
        location_hint="Form Locator 36a - From",
    ),
    FieldDefinition(
        name="occurrence_span_to_3",
        display_name="Occurrence Span To Date 3 (FL 36a)",
        field_type=FieldType.DATE,
        description="End date for occurrence span 3",
        required=False,
        location_hint="Form Locator 36a - To",
    ),
    FieldDefinition(
        name="occurrence_span_code_4",
        display_name="Occurrence Span Code 4 (FL 36b)",
        field_type=FieldType.STRING,
        description="Occurrence span code 4",
        required=False,
        location_hint="Form Locator 36b - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="occurrence_span_from_4",
        display_name="Occurrence Span From Date 4 (FL 36b)",
        field_type=FieldType.DATE,
        description="Start date for occurrence span 4",
        required=False,
        location_hint="Form Locator 36b - From",
    ),
    FieldDefinition(
        name="occurrence_span_to_4",
        display_name="Occurrence Span To Date 4 (FL 36b)",
        field_type=FieldType.DATE,
        description="End date for occurrence span 4",
        required=False,
        location_hint="Form Locator 36b - To",
    ),
]

# Value Codes (Form Locators 39-41)
VALUE_CODE_FIELDS = [
    FieldDefinition(
        name="value_code_1",
        display_name="Value Code 1 (FL 39a)",
        field_type=FieldType.STRING,
        description="Value code 1",
        required=False,
        location_hint="Form Locator 39a - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_1",
        display_name="Value Amount 1 (FL 39a)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 1",
        required=False,
        location_hint="Form Locator 39a - Amount",
    ),
    FieldDefinition(
        name="value_code_2",
        display_name="Value Code 2 (FL 39b)",
        field_type=FieldType.STRING,
        description="Value code 2",
        required=False,
        location_hint="Form Locator 39b - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_2",
        display_name="Value Amount 2 (FL 39b)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 2",
        required=False,
        location_hint="Form Locator 39b - Amount",
    ),
    FieldDefinition(
        name="value_code_3",
        display_name="Value Code 3 (FL 39c)",
        field_type=FieldType.STRING,
        description="Value code 3",
        required=False,
        location_hint="Form Locator 39c - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_3",
        display_name="Value Amount 3 (FL 39c)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 3",
        required=False,
        location_hint="Form Locator 39c - Amount",
    ),
    FieldDefinition(
        name="value_code_4",
        display_name="Value Code 4 (FL 39d)",
        field_type=FieldType.STRING,
        description="Value code 4",
        required=False,
        location_hint="Form Locator 39d - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_4",
        display_name="Value Amount 4 (FL 39d)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 4",
        required=False,
        location_hint="Form Locator 39d - Amount",
    ),
    FieldDefinition(
        name="value_code_5",
        display_name="Value Code 5 (FL 40a)",
        field_type=FieldType.STRING,
        description="Value code 5",
        required=False,
        location_hint="Form Locator 40a - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_5",
        display_name="Value Amount 5 (FL 40a)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 5",
        required=False,
        location_hint="Form Locator 40a - Amount",
    ),
    FieldDefinition(
        name="value_code_6",
        display_name="Value Code 6 (FL 40b)",
        field_type=FieldType.STRING,
        description="Value code 6",
        required=False,
        location_hint="Form Locator 40b - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_6",
        display_name="Value Amount 6 (FL 40b)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 6",
        required=False,
        location_hint="Form Locator 40b - Amount",
    ),
    FieldDefinition(
        name="value_code_7",
        display_name="Value Code 7 (FL 40c)",
        field_type=FieldType.STRING,
        description="Value code 7",
        required=False,
        location_hint="Form Locator 40c - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_7",
        display_name="Value Amount 7 (FL 40c)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 7",
        required=False,
        location_hint="Form Locator 40c - Amount",
    ),
    FieldDefinition(
        name="value_code_8",
        display_name="Value Code 8 (FL 40d)",
        field_type=FieldType.STRING,
        description="Value code 8",
        required=False,
        location_hint="Form Locator 40d - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_8",
        display_name="Value Amount 8 (FL 40d)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 8",
        required=False,
        location_hint="Form Locator 40d - Amount",
    ),
    FieldDefinition(
        name="value_code_9",
        display_name="Value Code 9 (FL 41a)",
        field_type=FieldType.STRING,
        description="Value code 9",
        required=False,
        location_hint="Form Locator 41a - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_9",
        display_name="Value Amount 9 (FL 41a)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 9",
        required=False,
        location_hint="Form Locator 41a - Amount",
    ),
    FieldDefinition(
        name="value_code_10",
        display_name="Value Code 10 (FL 41b)",
        field_type=FieldType.STRING,
        description="Value code 10",
        required=False,
        location_hint="Form Locator 41b - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_10",
        display_name="Value Amount 10 (FL 41b)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 10",
        required=False,
        location_hint="Form Locator 41b - Amount",
    ),
    FieldDefinition(
        name="value_code_11",
        display_name="Value Code 11 (FL 41c)",
        field_type=FieldType.STRING,
        description="Value code 11",
        required=False,
        location_hint="Form Locator 41c - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_11",
        display_name="Value Amount 11 (FL 41c)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 11",
        required=False,
        location_hint="Form Locator 41c - Amount",
    ),
    FieldDefinition(
        name="value_code_12",
        display_name="Value Code 12 (FL 41d)",
        field_type=FieldType.STRING,
        description="Value code 12",
        required=False,
        location_hint="Form Locator 41d - Code",
        pattern=r"^[A-Z0-9]{2}$",
    ),
    FieldDefinition(
        name="value_amount_12",
        display_name="Value Amount 12 (FL 41d)",
        field_type=FieldType.CURRENCY,
        description="Amount for value code 12",
        required=False,
        location_hint="Form Locator 41d - Amount",
    ),
]

# Revenue Codes and Service Lines (Form Locators 42-49)
SERVICE_LINE_FIELDS = [
    FieldDefinition(
        name="service_lines",
        display_name="Service Lines (FL 42-49)",
        field_type=FieldType.LIST,
        list_item_type=FieldType.OBJECT,
        nested_schema="ub04_service_line",
        description="List of service lines with revenue codes, HCPCS, and charges",
        required=True,
        location_hint="Form Locators 42-49 - Service detail rows",
    ),
    FieldDefinition(
        name="page_of",
        display_name="Page Number (FL 42)",
        field_type=FieldType.STRING,
        description="Page number in format 'X of Y'",
        required=False,
        location_hint="Form Locator 42 - Top row",
        pattern=r"^\d+\s+OF\s+\d+$",
    ),
    FieldDefinition(
        name="creation_date",
        display_name="Creation Date (FL 45)",
        field_type=FieldType.DATE,
        description="Date claim was created",
        required=False,
        location_hint="Form Locator 45",
    ),
    FieldDefinition(
        name="total_charges",
        display_name="Total Charges (FL 47)",
        field_type=FieldType.CURRENCY,
        description="Total charges for all service lines",
        required=True,
        location_hint="Form Locator 47 - Bottom totals row",
        min_value=0.01,
    ),
    FieldDefinition(
        name="total_non_covered_charges",
        display_name="Total Non-Covered Charges (FL 48)",
        field_type=FieldType.CURRENCY,
        description="Total non-covered charges",
        required=False,
        location_hint="Form Locator 48 - Bottom totals row",
        min_value=0,
    ),
]

# Payer Information (Form Locators 50-65)
PAYER_FIELDS = [
    # Primary Payer (A)
    FieldDefinition(
        name="payer_name_a",
        display_name="Payer Name A (FL 50A)",
        field_type=FieldType.STRING,
        description="Name of primary payer",
        required=True,
        location_hint="Form Locator 50A",
        examples=["MEDICARE", "BLUE CROSS", "AETNA"],
    ),
    FieldDefinition(
        name="health_plan_id_a",
        display_name="Health Plan ID A (FL 51A)",
        field_type=FieldType.STRING,
        description="Health plan ID for primary payer",
        required=False,
        location_hint="Form Locator 51A",
    ),
    FieldDefinition(
        name="release_info_a",
        display_name="Release of Information A (FL 52A)",
        field_type=FieldType.STRING,
        description="Release of information certification indicator",
        required=False,
        allowed_values=["Y", "I", "N"],
        location_hint="Form Locator 52A",
    ),
    FieldDefinition(
        name="assignment_benefits_a",
        display_name="Assignment of Benefits A (FL 53A)",
        field_type=FieldType.STRING,
        description="Assignment of benefits indicator",
        required=False,
        allowed_values=["Y", "N", "W"],
        location_hint="Form Locator 53A",
    ),
    FieldDefinition(
        name="prior_payments_a",
        display_name="Prior Payments A (FL 54A)",
        field_type=FieldType.CURRENCY,
        description="Prior payments from payer A",
        required=False,
        location_hint="Form Locator 54A",
        min_value=0,
    ),
    FieldDefinition(
        name="est_amount_due_a",
        display_name="Estimated Amount Due A (FL 55A)",
        field_type=FieldType.CURRENCY,
        description="Estimated amount due from payer A",
        required=False,
        location_hint="Form Locator 55A",
        min_value=0,
    ),
    FieldDefinition(
        name="billing_npi_a",
        display_name="Billing Provider NPI A (FL 56A)",
        field_type=FieldType.NPI,
        description="Billing provider NPI for payer A",
        required=True,
        location_hint="Form Locator 56A",
    ),
    FieldDefinition(
        name="insured_name_a",
        display_name="Insured Name A (FL 58A)",
        field_type=FieldType.NAME,
        description="Name of insured for payer A",
        required=True,
        location_hint="Form Locator 58A",
    ),
    FieldDefinition(
        name="patient_relationship_a",
        display_name="Patient Relationship A (FL 59A)",
        field_type=FieldType.STRING,
        description="Patient's relationship to insured A",
        required=True,
        location_hint="Form Locator 59A",
        pattern=r"^\d{2}$",
        examples=["01", "18", "19", "20", "21"],
    ),
    FieldDefinition(
        name="insured_id_a",
        display_name="Insured ID A (FL 60A)",
        field_type=FieldType.MEMBER_ID,
        description="Insured's unique ID for payer A",
        required=True,
        location_hint="Form Locator 60A",
    ),
    FieldDefinition(
        name="insured_group_name_a",
        display_name="Insured Group Name A (FL 61A)",
        field_type=FieldType.STRING,
        description="Insured's group name for payer A",
        required=False,
        location_hint="Form Locator 61A",
    ),
    FieldDefinition(
        name="insured_group_number_a",
        display_name="Insured Group Number A (FL 62A)",
        field_type=FieldType.GROUP_NUMBER,
        description="Insured's group number for payer A",
        required=False,
        location_hint="Form Locator 62A",
    ),
    FieldDefinition(
        name="treatment_authorization_a",
        display_name="Treatment Authorization A (FL 63A)",
        field_type=FieldType.STRING,
        description="Treatment authorization code for payer A",
        required=False,
        location_hint="Form Locator 63A",
    ),
    FieldDefinition(
        name="document_control_number_a",
        display_name="Document Control Number A (FL 64A)",
        field_type=FieldType.STRING,
        description="Document control number for payer A",
        required=False,
        location_hint="Form Locator 64A",
    ),
    FieldDefinition(
        name="employer_name_a",
        display_name="Employer Name A (FL 65A)",
        field_type=FieldType.STRING,
        description="Insured's employer name for payer A",
        required=False,
        location_hint="Form Locator 65A",
    ),
    # Secondary Payer (B)
    FieldDefinition(
        name="payer_name_b",
        display_name="Payer Name B (FL 50B)",
        field_type=FieldType.STRING,
        description="Name of secondary payer",
        required=False,
        location_hint="Form Locator 50B",
    ),
    FieldDefinition(
        name="health_plan_id_b",
        display_name="Health Plan ID B (FL 51B)",
        field_type=FieldType.STRING,
        description="Health plan ID for secondary payer",
        required=False,
        location_hint="Form Locator 51B",
    ),
    FieldDefinition(
        name="release_info_b",
        display_name="Release of Information B (FL 52B)",
        field_type=FieldType.STRING,
        description="Release of information indicator for payer B",
        required=False,
        allowed_values=["Y", "I", "N"],
        location_hint="Form Locator 52B",
    ),
    FieldDefinition(
        name="assignment_benefits_b",
        display_name="Assignment of Benefits B (FL 53B)",
        field_type=FieldType.STRING,
        description="Assignment of benefits indicator for payer B",
        required=False,
        allowed_values=["Y", "N", "W"],
        location_hint="Form Locator 53B",
    ),
    FieldDefinition(
        name="prior_payments_b",
        display_name="Prior Payments B (FL 54B)",
        field_type=FieldType.CURRENCY,
        description="Prior payments from payer B",
        required=False,
        location_hint="Form Locator 54B",
        min_value=0,
    ),
    FieldDefinition(
        name="est_amount_due_b",
        display_name="Estimated Amount Due B (FL 55B)",
        field_type=FieldType.CURRENCY,
        description="Estimated amount due from payer B",
        required=False,
        location_hint="Form Locator 55B",
        min_value=0,
    ),
    FieldDefinition(
        name="billing_npi_b",
        display_name="Billing Provider NPI B (FL 56B)",
        field_type=FieldType.NPI,
        description="Billing provider NPI for payer B",
        required=False,
        location_hint="Form Locator 56B",
    ),
    FieldDefinition(
        name="insured_name_b",
        display_name="Insured Name B (FL 58B)",
        field_type=FieldType.NAME,
        description="Name of insured for payer B",
        required=False,
        location_hint="Form Locator 58B",
    ),
    FieldDefinition(
        name="patient_relationship_b",
        display_name="Patient Relationship B (FL 59B)",
        field_type=FieldType.STRING,
        description="Patient's relationship to insured B",
        required=False,
        location_hint="Form Locator 59B",
        pattern=r"^\d{2}$",
    ),
    FieldDefinition(
        name="insured_id_b",
        display_name="Insured ID B (FL 60B)",
        field_type=FieldType.MEMBER_ID,
        description="Insured's unique ID for payer B",
        required=False,
        location_hint="Form Locator 60B",
    ),
    FieldDefinition(
        name="insured_group_name_b",
        display_name="Insured Group Name B (FL 61B)",
        field_type=FieldType.STRING,
        description="Insured's group name for payer B",
        required=False,
        location_hint="Form Locator 61B",
    ),
    FieldDefinition(
        name="insured_group_number_b",
        display_name="Insured Group Number B (FL 62B)",
        field_type=FieldType.GROUP_NUMBER,
        description="Insured's group number for payer B",
        required=False,
        location_hint="Form Locator 62B",
    ),
    FieldDefinition(
        name="treatment_authorization_b",
        display_name="Treatment Authorization B (FL 63B)",
        field_type=FieldType.STRING,
        description="Treatment authorization code for payer B",
        required=False,
        location_hint="Form Locator 63B",
    ),
    FieldDefinition(
        name="document_control_number_b",
        display_name="Document Control Number B (FL 64B)",
        field_type=FieldType.STRING,
        description="Document control number for payer B",
        required=False,
        location_hint="Form Locator 64B",
    ),
    FieldDefinition(
        name="employer_name_b",
        display_name="Employer Name B (FL 65B)",
        field_type=FieldType.STRING,
        description="Insured's employer name for payer B",
        required=False,
        location_hint="Form Locator 65B",
    ),
    # Tertiary Payer (C)
    FieldDefinition(
        name="payer_name_c",
        display_name="Payer Name C (FL 50C)",
        field_type=FieldType.STRING,
        description="Name of tertiary payer",
        required=False,
        location_hint="Form Locator 50C",
    ),
    FieldDefinition(
        name="health_plan_id_c",
        display_name="Health Plan ID C (FL 51C)",
        field_type=FieldType.STRING,
        description="Health plan ID for tertiary payer",
        required=False,
        location_hint="Form Locator 51C",
    ),
    FieldDefinition(
        name="insured_name_c",
        display_name="Insured Name C (FL 58C)",
        field_type=FieldType.NAME,
        description="Name of insured for payer C",
        required=False,
        location_hint="Form Locator 58C",
    ),
    FieldDefinition(
        name="insured_id_c",
        display_name="Insured ID C (FL 60C)",
        field_type=FieldType.MEMBER_ID,
        description="Insured's unique ID for payer C",
        required=False,
        location_hint="Form Locator 60C",
    ),
]

# Diagnosis Codes (Form Locators 66-75)
DIAGNOSIS_FIELDS = [
    FieldDefinition(
        name="principal_diagnosis",
        display_name="Principal Diagnosis (FL 67)",
        field_type=FieldType.ICD10_CODE,
        description="Principal diagnosis code (ICD-10-CM)",
        required=True,
        location_hint="Form Locator 67",
        examples=["I10", "E11.9", "J06.9"],
    ),
    FieldDefinition(
        name="admitting_diagnosis",
        display_name="Admitting Diagnosis (FL 69)",
        field_type=FieldType.ICD10_CODE,
        description="Admitting diagnosis code",
        required=False,
        location_hint="Form Locator 69",
    ),
    FieldDefinition(
        name="diagnosis_a",
        display_name="Diagnosis Code A (FL 67A)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code A",
        required=False,
        location_hint="Form Locator 67A",
    ),
    FieldDefinition(
        name="diagnosis_b",
        display_name="Diagnosis Code B (FL 67B)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code B",
        required=False,
        location_hint="Form Locator 67B",
    ),
    FieldDefinition(
        name="diagnosis_c",
        display_name="Diagnosis Code C (FL 67C)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code C",
        required=False,
        location_hint="Form Locator 67C",
    ),
    FieldDefinition(
        name="diagnosis_d",
        display_name="Diagnosis Code D (FL 67D)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code D",
        required=False,
        location_hint="Form Locator 67D",
    ),
    FieldDefinition(
        name="diagnosis_e",
        display_name="Diagnosis Code E (FL 67E)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code E",
        required=False,
        location_hint="Form Locator 67E",
    ),
    FieldDefinition(
        name="diagnosis_f",
        display_name="Diagnosis Code F (FL 67F)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code F",
        required=False,
        location_hint="Form Locator 67F",
    ),
    FieldDefinition(
        name="diagnosis_g",
        display_name="Diagnosis Code G (FL 67G)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code G",
        required=False,
        location_hint="Form Locator 67G",
    ),
    FieldDefinition(
        name="diagnosis_h",
        display_name="Diagnosis Code H (FL 67H)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code H",
        required=False,
        location_hint="Form Locator 67H",
    ),
    FieldDefinition(
        name="diagnosis_i",
        display_name="Diagnosis Code I (FL 67I)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code I",
        required=False,
        location_hint="Form Locator 67I",
    ),
    FieldDefinition(
        name="diagnosis_j",
        display_name="Diagnosis Code J (FL 67J)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code J",
        required=False,
        location_hint="Form Locator 67J",
    ),
    FieldDefinition(
        name="diagnosis_k",
        display_name="Diagnosis Code K (FL 67K)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code K",
        required=False,
        location_hint="Form Locator 67K",
    ),
    FieldDefinition(
        name="diagnosis_l",
        display_name="Diagnosis Code L (FL 67L)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code L",
        required=False,
        location_hint="Form Locator 67L",
    ),
    FieldDefinition(
        name="diagnosis_m",
        display_name="Diagnosis Code M (FL 67M)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code M",
        required=False,
        location_hint="Form Locator 67M",
    ),
    FieldDefinition(
        name="diagnosis_n",
        display_name="Diagnosis Code N (FL 67N)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code N",
        required=False,
        location_hint="Form Locator 67N",
    ),
    FieldDefinition(
        name="diagnosis_o",
        display_name="Diagnosis Code O (FL 67O)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code O",
        required=False,
        location_hint="Form Locator 67O",
    ),
    FieldDefinition(
        name="diagnosis_p",
        display_name="Diagnosis Code P (FL 67P)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code P",
        required=False,
        location_hint="Form Locator 67P",
    ),
    FieldDefinition(
        name="diagnosis_q",
        display_name="Diagnosis Code Q (FL 67Q)",
        field_type=FieldType.ICD10_CODE,
        description="Other diagnosis code Q",
        required=False,
        location_hint="Form Locator 67Q",
    ),
    FieldDefinition(
        name="patient_reason_dx_a",
        display_name="Patient Reason Diagnosis A (FL 70a)",
        field_type=FieldType.ICD10_CODE,
        description="Patient's reason for visit - diagnosis A",
        required=False,
        location_hint="Form Locator 70a",
    ),
    FieldDefinition(
        name="patient_reason_dx_b",
        display_name="Patient Reason Diagnosis B (FL 70b)",
        field_type=FieldType.ICD10_CODE,
        description="Patient's reason for visit - diagnosis B",
        required=False,
        location_hint="Form Locator 70b",
    ),
    FieldDefinition(
        name="patient_reason_dx_c",
        display_name="Patient Reason Diagnosis C (FL 70c)",
        field_type=FieldType.ICD10_CODE,
        description="Patient's reason for visit - diagnosis C",
        required=False,
        location_hint="Form Locator 70c",
    ),
    FieldDefinition(
        name="pps_code",
        display_name="PPS Code (FL 71)",
        field_type=FieldType.STRING,
        description="Prospective Payment System code (DRG)",
        required=False,
        location_hint="Form Locator 71",
        pattern=r"^\d{3}$",
    ),
    FieldDefinition(
        name="eci_1",
        display_name="External Cause of Injury 1 (FL 72a)",
        field_type=FieldType.ICD10_CODE,
        description="External cause of injury code 1",
        required=False,
        location_hint="Form Locator 72a",
    ),
    FieldDefinition(
        name="eci_2",
        display_name="External Cause of Injury 2 (FL 72b)",
        field_type=FieldType.ICD10_CODE,
        description="External cause of injury code 2",
        required=False,
        location_hint="Form Locator 72b",
    ),
    FieldDefinition(
        name="eci_3",
        display_name="External Cause of Injury 3 (FL 72c)",
        field_type=FieldType.ICD10_CODE,
        description="External cause of injury code 3",
        required=False,
        location_hint="Form Locator 72c",
    ),
]

# Procedure Codes (Form Locators 74)
PROCEDURE_FIELDS = [
    FieldDefinition(
        name="principal_procedure",
        display_name="Principal Procedure Code (FL 74)",
        field_type=FieldType.STRING,
        description="Principal procedure code (ICD-10-PCS for inpatient)",
        required=False,
        location_hint="Form Locator 74",
        pattern=r"^[A-Z0-9]{7}$",
    ),
    FieldDefinition(
        name="principal_procedure_date",
        display_name="Principal Procedure Date (FL 74)",
        field_type=FieldType.DATE,
        description="Date of principal procedure",
        required=False,
        location_hint="Form Locator 74 - Date column",
    ),
    FieldDefinition(
        name="other_procedure_a",
        display_name="Other Procedure Code A (FL 74a)",
        field_type=FieldType.STRING,
        description="Other procedure code A",
        required=False,
        location_hint="Form Locator 74a",
        pattern=r"^[A-Z0-9]{7}$",
    ),
    FieldDefinition(
        name="other_procedure_date_a",
        display_name="Other Procedure Date A (FL 74a)",
        field_type=FieldType.DATE,
        description="Date of other procedure A",
        required=False,
        location_hint="Form Locator 74a - Date column",
    ),
    FieldDefinition(
        name="other_procedure_b",
        display_name="Other Procedure Code B (FL 74b)",
        field_type=FieldType.STRING,
        description="Other procedure code B",
        required=False,
        location_hint="Form Locator 74b",
        pattern=r"^[A-Z0-9]{7}$",
    ),
    FieldDefinition(
        name="other_procedure_date_b",
        display_name="Other Procedure Date B (FL 74b)",
        field_type=FieldType.DATE,
        description="Date of other procedure B",
        required=False,
        location_hint="Form Locator 74b - Date column",
    ),
    FieldDefinition(
        name="other_procedure_c",
        display_name="Other Procedure Code C (FL 74c)",
        field_type=FieldType.STRING,
        description="Other procedure code C",
        required=False,
        location_hint="Form Locator 74c",
        pattern=r"^[A-Z0-9]{7}$",
    ),
    FieldDefinition(
        name="other_procedure_date_c",
        display_name="Other Procedure Date C (FL 74c)",
        field_type=FieldType.DATE,
        description="Date of other procedure C",
        required=False,
        location_hint="Form Locator 74c - Date column",
    ),
    FieldDefinition(
        name="other_procedure_d",
        display_name="Other Procedure Code D (FL 74d)",
        field_type=FieldType.STRING,
        description="Other procedure code D",
        required=False,
        location_hint="Form Locator 74d",
        pattern=r"^[A-Z0-9]{7}$",
    ),
    FieldDefinition(
        name="other_procedure_date_d",
        display_name="Other Procedure Date D (FL 74d)",
        field_type=FieldType.DATE,
        description="Date of other procedure D",
        required=False,
        location_hint="Form Locator 74d - Date column",
    ),
    FieldDefinition(
        name="other_procedure_e",
        display_name="Other Procedure Code E (FL 74e)",
        field_type=FieldType.STRING,
        description="Other procedure code E",
        required=False,
        location_hint="Form Locator 74e",
        pattern=r"^[A-Z0-9]{7}$",
    ),
    FieldDefinition(
        name="other_procedure_date_e",
        display_name="Other Procedure Date E (FL 74e)",
        field_type=FieldType.DATE,
        description="Date of other procedure E",
        required=False,
        location_hint="Form Locator 74e - Date column",
    ),
]

# Attending/Other Physicians (Form Locators 76-79)
PHYSICIAN_FIELDS = [
    FieldDefinition(
        name="attending_npi",
        display_name="Attending Physician NPI (FL 76)",
        field_type=FieldType.NPI,
        description="Attending physician's NPI",
        required=True,
        location_hint="Form Locator 76 - NPI column",
    ),
    FieldDefinition(
        name="attending_qualifier",
        display_name="Attending Physician Qualifier (FL 76)",
        field_type=FieldType.STRING,
        description="Attending physician ID qualifier",
        required=False,
        location_hint="Form Locator 76 - Qual column",
    ),
    FieldDefinition(
        name="attending_name",
        display_name="Attending Physician Name (FL 76)",
        field_type=FieldType.NAME,
        description="Attending physician's last and first name",
        required=True,
        location_hint="Form Locator 76 - Name column",
    ),
    FieldDefinition(
        name="operating_npi",
        display_name="Operating Physician NPI (FL 77)",
        field_type=FieldType.NPI,
        description="Operating physician's NPI",
        required=False,
        location_hint="Form Locator 77 - NPI column",
    ),
    FieldDefinition(
        name="operating_qualifier",
        display_name="Operating Physician Qualifier (FL 77)",
        field_type=FieldType.STRING,
        description="Operating physician ID qualifier",
        required=False,
        location_hint="Form Locator 77 - Qual column",
    ),
    FieldDefinition(
        name="operating_name",
        display_name="Operating Physician Name (FL 77)",
        field_type=FieldType.NAME,
        description="Operating physician's last and first name",
        required=False,
        location_hint="Form Locator 77 - Name column",
    ),
    FieldDefinition(
        name="other_provider_1_npi",
        display_name="Other Provider 1 NPI (FL 78)",
        field_type=FieldType.NPI,
        description="Other provider 1 NPI",
        required=False,
        location_hint="Form Locator 78 - NPI column",
    ),
    FieldDefinition(
        name="other_provider_1_qualifier",
        display_name="Other Provider 1 Qualifier (FL 78)",
        field_type=FieldType.STRING,
        description="Other provider 1 qualifier code",
        required=False,
        location_hint="Form Locator 78 - Qual column",
    ),
    FieldDefinition(
        name="other_provider_1_name",
        display_name="Other Provider 1 Name (FL 78)",
        field_type=FieldType.NAME,
        description="Other provider 1 name",
        required=False,
        location_hint="Form Locator 78 - Name column",
    ),
    FieldDefinition(
        name="other_provider_2_npi",
        display_name="Other Provider 2 NPI (FL 79)",
        field_type=FieldType.NPI,
        description="Other provider 2 NPI",
        required=False,
        location_hint="Form Locator 79 - NPI column",
    ),
    FieldDefinition(
        name="other_provider_2_qualifier",
        display_name="Other Provider 2 Qualifier (FL 79)",
        field_type=FieldType.STRING,
        description="Other provider 2 qualifier code",
        required=False,
        location_hint="Form Locator 79 - Qual column",
    ),
    FieldDefinition(
        name="other_provider_2_name",
        display_name="Other Provider 2 Name (FL 79)",
        field_type=FieldType.NAME,
        description="Other provider 2 name",
        required=False,
        location_hint="Form Locator 79 - Name column",
    ),
]

# Remarks and Additional Information (Form Locators 80-81)
REMARKS_FIELDS = [
    FieldDefinition(
        name="remarks",
        display_name="Remarks (FL 80)",
        field_type=FieldType.STRING,
        description="Additional remarks or special instructions",
        required=False,
        location_hint="Form Locator 80",
    ),
    FieldDefinition(
        name="code_code_field",
        display_name="Code-Code Field (FL 81)",
        field_type=FieldType.LIST,
        list_item_type=FieldType.OBJECT,
        nested_schema="ub04_code_code",
        description="Code-code qualifier and code pairs",
        required=False,
        location_hint="Form Locator 81",
    ),
]


# =============================================================================
# Cross-Field Validation Rules
# =============================================================================

UB04_CROSS_FIELD_RULES = [
    # V3 Phase 5 — Sum reconciliation. UB-04 Form Locator 47 ("Total
    # Charges") should equal the sum of FL47 across all revenue-code
    # service lines. Like CMS-1500 we keep this advisory because
    # rounding/discount deltas are common; the validator surfaces
    # mismatches for human review without blocking.
    CrossFieldRule(
        source_field="service_lines",
        target_field="total_charges",
        operator=RuleOperator.SUM_EQUALS,
        value="total_charges",  # per-line field on each service line
        error_message=(
            "Total charges (FL47 summary) should equal the sum of "
            "line-item charges across service lines."
        ),
        severity="warning",
    ),
    # V3 Phase 5 — diagnosis presence: a UB-04 with reported service
    # lines must carry at least the principal diagnosis (FL67).
    CrossFieldRule(
        source_field="service_lines",
        target_field="principal_diagnosis",
        operator=RuleOperator.REQUIRES_IF,
        error_message=(
            "Principal diagnosis (FL67) must be present when service "
            "lines are reported."
        ),
        severity="error",
    ),
    # Statement period from must be before to
    CrossFieldRule(
        source_field="statement_from_date",
        target_field="statement_to_date",
        operator=RuleOperator.DATE_BEFORE,
        error_message="Statement From date must be before Statement To date",
    ),
    # Patient DOB must be before admission date
    CrossFieldRule(
        source_field="patient_dob",
        target_field="admission_date",
        operator=RuleOperator.DATE_BEFORE,
        error_message="Patient date of birth must be before admission date",
    ),
    # Admission date must be within statement period
    CrossFieldRule(
        source_field="admission_date",
        target_field="statement_to_date",
        operator=RuleOperator.DATE_BEFORE,
        error_message="Admission date must be within statement period",
        severity="warning",
    ),
    # Total charges should be greater than 0
    CrossFieldRule(
        source_field="total_charges",
        target_field="total_non_covered_charges",
        operator=RuleOperator.GREATER_EQUAL,
        error_message="Total charges should be greater than or equal to non-covered charges",
        severity="warning",
    ),
    # If secondary payer exists, must have primary payer info
    CrossFieldRule(
        source_field="payer_name_a",
        target_field="payer_name_b",
        operator=RuleOperator.REQUIRES_IF,
        error_message="Primary payer (Payer A) required if secondary payer (Payer B) is present",
    ),
    # If operating physician NPI present, name should be present
    CrossFieldRule(
        source_field="operating_npi",
        target_field="operating_name",
        operator=RuleOperator.REQUIRES_IF,
        error_message="Operating physician name required when NPI is provided",
    ),
    # Principal procedure requires a date
    CrossFieldRule(
        source_field="principal_procedure",
        target_field="principal_procedure_date",
        operator=RuleOperator.REQUIRES_IF,
        error_message="Principal procedure date required when procedure code is provided",
    ),
]


# =============================================================================
# UB-04 Schema Definition
# =============================================================================

UB04_SCHEMA = DocumentSchema(
    name="ub04",
    display_name="UB-04 (CMS-1450) Institutional Claim",
    document_type=DocumentType.UB_04,
    description="Uniform billing form used by institutional providers (hospitals, SNFs, home health) for Medicare, Medicaid, and most commercial payers",
    version="1.0.0",
    fields=(
        PROVIDER_FIELDS
        + PATIENT_FIELDS
        + CONDITION_CODE_FIELDS
        + OCCURRENCE_FIELDS
        + OCCURRENCE_SPAN_FIELDS
        + VALUE_CODE_FIELDS
        + SERVICE_LINE_FIELDS
        + PAYER_FIELDS
        + DIAGNOSIS_FIELDS
        + PROCEDURE_FIELDS
        + PHYSICIAN_FIELDS
        + REMARKS_FIELDS
    ),
    cross_field_rules=UB04_CROSS_FIELD_RULES,
    required_sections=[
        "Provider Information",
        "Patient Information",
        "Admission Information",
        "Type of Bill",
        "Service Lines",
        "Total Charges",
        "Payer Information",
        "Diagnosis Codes",
        "Attending Physician",
    ],
    classification_hints=[
        "UB-04",
        "UB04",
        "CMS-1450",
        "CMS1450",
        "UNIFORM BILL",
        "INSTITUTIONAL CLAIM",
        "HOSPITAL CLAIM",
        "TYPE OF BILL",
        "REVENUE CODE",
        "FORM LOCATOR",
        "PATIENT CONTROL NUMBER",
        "ADMISSION DATE",
        "DISCHARGE STATUS",
        "DRG",
        "NUBC",
    ],
)


def register_ub04_schema() -> None:
    """Register UB-04 schema with the global registry."""
    registry = SchemaRegistry()
    registry.register(UB04_SCHEMA)


# Auto-register on import
register_ub04_schema()
